name: islets-omics
channels:
  - conda-forge
dependencies:
  # Core scientific computing
  - python>=3.10
  - numpy>=1.26.0
  - pandas>=2.2.0
  - scipy>=1.13.0

  # Machine learning
  - scikit-learn>=1.5.0

  # Visualization
  - matplotlib>=3.9.0
  - seaborn>=0.13.0

  # Bioinformatics
  - biopython>=1.84
  - biomart>=0.9.2

  # Single-cell/omics analysis
  - anndata>=0.10.0

  # Additional utilities
  - regex>=2024.0.0
  - adjusttext>=1.2.0

  # Jupyter
  - jupyter>=1.1.0
  - ipykernel>=6.29.0
